import { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const virgil = localFont({ src: '../../public/fonts/Virgil.woff2' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`bg-red-500 ${virgil.className}`}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
